# Generated by Django 4.1 on 2022-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_colleges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientcomp_name', models.CharField(max_length=80)),
                ('Work_status', models.CharField(max_length=20)),
                ('comp_logo', models.ImageField(null=True, upload_to='client')),
            ],
        ),
    ]
