# Generated by Django 4.1 on 2022-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_clientscompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_comp_name', models.CharField(max_length=80)),
                ('pro_comp_logo', models.ImageField(null=True, upload_to='productcompany')),
            ],
        ),
    ]
