# Generated by Django 4.1 on 2022-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_productcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_company', models.CharField(max_length=60)),
                ('product_price', models.CharField(max_length=20)),
                ('product_details', models.TextField()),
                ('product_img', models.ImageField(null=True, upload_to='product')),
            ],
        ),
    ]
