# Generated by Django 4.1 on 2022-08-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_category', models.CharField(max_length=60)),
                ('w_status', models.CharField(max_length=20)),
                ('w_details', models.TextField()),
                ('w_img', models.ImageField(null=True, upload_to='works')),
            ],
        ),
    ]
